import Head from 'next/head'
import Layout from '../components/Layout'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '../components/Animatedtext'
import Link from 'next/link'
import LinkArrow from '../../public/images/svgs/external-link.svg'
import HireMe from '../components/HireMe'
import React, { forwardRef } from 'react'




// function Contact() {
//   return (
//     <Link href="/about" passHref legacyBehavior>
//       <MyButton />
//     </Link>
//   )
// }

export default function Home() {
  const MyButton = React.forwardRef(({ onClick, href }, ref) => {
    return (
      <a href={href} onClick={onClick} ref={ref}>
        Contact
      </a>
    )
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout classname='pt-0 md:pt-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} className='w-full h-auto lg:hidden md:inline-block md:w-full'
                priority
                sizes='{max-width: 768px} 100vw,
              {max-width: 1200px} 50vw,
              50vw'
              />
            </div>
            <div className='w-1/2 flex flex-col items-start self-center lg:w-full lg:text-center'>
              <AnimatedText text="Turning Vision Into Reality With Code And Design" classname='text-black 
              !text-left xl: !text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:text-3xl' />
              <p className='my-4 text-center font-medium self-start lg:self-center md:text-sm sm:text-xs'>Skill is a myth. It is all dedication and crystal focus!</p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="https://drive.google.com/file/d/1Y4CC2a-tEA-N9ueOz0F2YPvGO_pY1Rk5/view?usp=share_link" target={'_blank'}
                  className="flex items-center bg-dark text-light py-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
                md:p-2 md:px-4 md:text-base"
                  download={true}>
                  Resume
                  <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link href="" passHref legacyBehavior
                  className='ml-4 text-lg font-medium text-dark underline hover:underline-offset-2 dark:text-light md:text-base '><MyButton /></Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  )
}
